version: '3'

services:
  petshop-db:
    image: postgres:16
    container_name: petshop-db-container
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - petshop-network

  petshop-pgbouncer:
    image: brainsam/pgbouncer:1.12.0
    container_name: petshop-pgbouncer-container
    ports:
      - 6433:6432
    environment:
      - DB_HOST=petshop-db
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
      - DB_port=${DATABASE_PORT}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
    depends_on:
      - petshop-db
    networks:
      - petshop-network

  petshop-app:
    build: .
    container_name: petshop-app-container
    ports:
      - 3000:3000
    depends_on:
      - petshop-db
      - petshop-pgbouncer
    environment:
      - NODE_ENV=${NODE_ENV}
      # - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@petshop-db:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@petshop-pgbouncer:6432/${DATABASE_NAME}?schema=public&pgbouncer=true
      - DATABASE_URL_UNPOOLED=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@petshop-db:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
    networks:
      - petshop-network

networks:
  petshop-network:
    driver: bridge