version: '3'

services:
  petshop-db:
    image: postgres:16
    container_name: petshop-db-container
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - petshop-network
  
  # petshop-app:
  #   build: .
  #   links:
  #     - petshop-db
  #   container_name: petshop-app-container
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - petshop-db
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - petshop-network

networks:
  petshop-network:
    driver: bridge