import './globals.css';
import type { Metadata } from 'next';

import StoreProvider from './StoreProvider';
import Header from './components/Header';

import { getCart } from '@/api/cart';

import { ClerkProvider } from '@clerk/nextjs';
import { Footer } from './components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCart();

  return (
    <ClerkProvider>
      <html lang='en'>
        <body>
          <StoreProvider cart={cart}>
            {/* Header should not have action just redirect to checkoutpage */}
            <Header />
            <main className=''>{children}</main>
            <Footer />
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
