export const countries = [
  {
    name: "United States",
    code: "US",
    states: [
      { name: "Alabama", code: "AL" },
      { name: "Alaska", code: "AK" },
      { name: "Arizona", code: "AZ" },
      { name: "Arkansas", code: "AR" },
      { name: "California", code: "CA" },
      { name: "Colorado", code: "CO" },
      { name: "Connecticut", code: "CT" },
      { name: "Delaware", code: "DE" },
      { name: "Florida", code: "FL" },
      { name: "Georgia", code: "GA" },
      { name: "Hawaii", code: "HI" },
      { name: "Idaho", code: "ID" },
      { name: "Illinois", code: "IL" },
      { name: "Indiana", code: "IN" },
      { name: "Iowa", code: "IA" },
      { name: "Kansas", code: "KS" },
      { name: "Kentucky", code: "KY" },
      { name: "Louisiana", code: "LA" },
      { name: "Maine", code: "ME" },
      { name: "Maryland", code: "MD" },
      { name: "Massachusetts", code: "MA" },
      { name: "Michigan", code: "MI" },
      { name: "Minnesota", code: "MN" },
      { name: "Mississippi", code: "MS" },
      { name: "Missouri", code: "MO" },
      { name: "Montana", code: "MT" },
      { name: "Nebraska", code: "NE" },
      { name: "Nevada", code: "NV" },
      { name: "New Hampshire", code: "NH" },
      { name: "New Jersey", code: "NJ" },
      { name: "New Mexico", code: "NM" },
      { name: "New York", code: "NY" },
      { name: "North Carolina", code: "NC" },
      { name: "North Dakota", code: "ND" },
      { name: "Ohio", code: "OH" },
      { name: "Oklahoma", code: "OK" },
      { name: "Oregon", code: "OR" },
      { name: "Pennsylvania", code: "PA" },
      { name: "Rhode Island", code: "RI" },
      { name: "South Carolina", code: "SC" },
      { name: "South Dakota", code: "SD" },
      { name: "Tennessee", code: "TN" },
      { name: "Texas", code: "TX" },
      { name: "Utah", code: "UT" },
      { name: "Vermont", code: "VT" },
      { name: "Virginia", code: "VA" },
      { name: "Washington", code: "WA" },
      { name: "West Virginia", code: "WV" },
      { name: "Wisconsin", code: "WI" },
      { name: "Wyoming", code: "WY" },
    ],
  },
  {
    name: "Canada",
    code: "CA",
    states: [
      { name: "Alberta", code: "AB" },
      { name: "British Columbia", code: "BC" },
      { name: "Manitoba", code: "MB" },
      { name: "New Brunswick", code: "NB" },
      { name: "Newfoundland and Labrador", code: "NL" },
      { name: "Northwest Territories", code: "NT" },
      { name: "Nova Scotia", code: "NS" },
      { name: "Nunavut", code: "NU" },
      { name: "Ontario", code: "ON" },
      { name: "Prince Edward Island", code: "PE" },
      { name: "Quebec", code: "QC" },
      { name: "Saskatchewan", code: "SK" },
      { name: "Yukon", code: "YT" },
    ],
  },
  {
    name: "Mexico",
    code: "MX",
    states: [
      { name: "Aguascalientes", code: "AG" },
      { name: "Baja California", code: "BC" },
      { name: "Baja California Sur", code: "BS" },
      { name: "Campeche", code: "CM" },
      { name: "Chiapas", code: "CS" },
      { name: "Chihuahua", code: "CH" },
      { name: "Coahuila", code: "CO" },
      { name: "Colima", code: "CL" },
      { name: "Durango", code: "DG" },
      { name: "Guanajuato", code: "GT" },
      { name: "Guerrero", code: "GR" },
      { name: "Hidalgo", code: "HG" },
      { name: "Jalisco", code: "JA" },
      { name: "Mexico City", code: "DF" },
      { name: "Michoacán", code: "MI" },
      { name: "Morelos", code: "MO" },
      { name: "Nayarit", code: "NA" },
      { name: "Nuevo León", code: "NL" },
      { name: "Oaxaca", code: "OA" },
      { name: "Puebla", code: "PU" },
      { name: "Querétaro", code: "QE" },
      { name: "Quintana Roo", code: "QR" },
      { name: "San Luis Potosí", code: "SL" },
      { name: "Sinaloa", code: "SI" },
      { name: "Sonora", code: "SO" },
      { name: "Tabasco", code: "TB" },
      { name: "Tamaulipas", code: "TM" },
      { name: "Tlaxcala", code: "TL" },
      { name: "Veracruz", code: "VE" },
      { name: "Yucatán", code: "YU" },
      { name: "Zacatecas", code: "ZA" },
    ],
  },
  {
    name: "Colombia",
    code: "CO",
    states: [
      { name: "Amazonas", code: "AMA" },
      { name: "Antioquia", code: "ANT" },
      { name: "Arauca", code: "ARA" },
      { name: "Atlántico", code: "ATL" },
      { name: "Bolívar", code: "BOL" },
      { name: "Boyacá", code: "BOY" },
      { name: "Caldas", code: "CAL" },
      { name: "Caquetá", code: "CAQ" },
      { name: "Casanare", code: "CAS" },
      { name: "Cauca", code: "CAU" },
      { name: "Cesar", code: "CES" },
      { name: "Chocó", code: "CHO" },
      { name: "Córdoba", code: "COR" },
      { name: "Cundinamarca", code: "CUN" },
      { name: "Guainía", code: "GUA" },
      { name: "Guaviare", code: "GUV" },
      { name: "Huila", code: "HUI" },
      { name: "La Guajira", code: "LAG" },
      { name: "Magdalena", code: "MAG" },
      { name: "Meta", code: "MET" },
      { name: "Nariño", code: "NAR" },
      { name: "Norte de Santander", code: "NSA" },
      { name: "Putumayo", code: "PUT" },
      { name: "Quindío", code: "QUI" },
      { name: "Risaralda", code: "RIS" },
      { name: "San Andrés y Providencia", code: "SAP" },
      { name: "Santander", code: "SAN" },
      { name: "Sucre", code: "SUC" },
      { name: "Tolima", code: "TOL" },
      { name: "Valle del Cauca", code: "VAC" },
      { name: "Vaupés", code: "VAU" },
      { name: "Vichada", code: "VID" },
    ],
  },
];
